# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
