# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0002_auto_20161025_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='office',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='regId',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='instructor',
        ),
        migrations.AddField(
            model_name='classroom',
            name='instructor',
            field=models.ManyToManyField(to='buzzer.Instructor'),
        ),
    ]
