# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0003_auto_20161101_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
