# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0006_auto_20161101_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='instructor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
